apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: o7ov5jwib-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/o7ov5jwib-java-quarkus-gitops